openapi: 3.0.0
info:
  title: Snippety-Snip API - Snippets
  version: 1.0.0

paths:
  /api/snippets:
    post:
      summary: Create a new snippet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
                - language
              properties:
                title:
                  type: string
                  maxLength: 100
                content:
                  type: string
                  maxLength: 50000
                language:
                  type: string
                  description: Language identifier selected from the supported list
                  enum:
                    - c-sharp
                    - c-plus-plus
                    - css
                    - go
                    - html
                    - java
                    - javascript
                    - json
                    - kotlin
                    - markdown
                    - other
                    - php
                    - powershell
                    - python
                    - ruby
                    - rust
                    - shell-bash
                    - sql
                    - swift
                    - typescript
                    - yaml
      responses:
        "201":
          description: Snippet created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Snippet"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    Snippet:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        language:
          type: string
          description: Language identifier stored with the snippet
          enum:
            - c-sharp
            - c-plus-plus
            - css
            - go
            - html
            - java
            - javascript
            - json
            - kotlin
            - markdown
            - other
            - php
            - powershell
            - python
            - ruby
            - rust
            - shell-bash
            - sql
            - swift
            - typescript
            - yaml
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
