import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeContext";
import { ThemeToggle } from "@/components/ui/ThemeToggle";
import { CodeBlockSettingsProvider } from "@/contexts/CodeBlockSettingsContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeInitScript = `
(function () {
  try {
    var storageKey = 'snippety-theme';
    var storedTheme = window.localStorage.getItem(storageKey);
    var prefersLight = window.matchMedia && window.matchMedia('(prefers-color-scheme: light)').matches;
    var theme = storedTheme === 'light' || storedTheme === 'dark'
      ? storedTheme
      : (prefersLight ? 'light' : 'dark');
    var targets = [document.documentElement, document.body];
    targets.forEach(function (target) {
      if (!target) {
        return;
      }
      target.classList.remove('theme-light', 'theme-dark');
      target.classList.add(theme === 'light' ? 'theme-light' : 'theme-dark');
    });
  } catch (error) {
    // Ignore hydration theme errors
  }
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} theme-dark`}>
        <Script id="theme-init" strategy="beforeInteractive" dangerouslySetInnerHTML={{ __html: themeInitScript }} />
        <ThemeProvider>
          <CodeBlockSettingsProvider>
            <div className="theme-toggle-container">
              <ThemeToggle />
            </div>
            {children}
          </CodeBlockSettingsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
